### ISSUE TITLE
InvalidOperationException: Cannot override system-specified headers

### ISSUE THREAD

**Issue by frankhan95** [globalstats-io/unity-library#4]
I'm getting  the following error when trying to POST:
`InvalidOperationException: Cannot override system-specified headers
UnityEngine.Networking.UnityWebRequest.SetRequestHeader (System.String name, System.String value) (at C:/buildslave/unity/build/Modules/UnityWebRequest/Public/UnityWebRequest.bindings.cs:484)
UnityEngine.WWW..ctor (System.String url, System.Byte[] postData, System.Collections.Generic.Dictionary2 headers) (at C:/buildslave/unity/build/Modules/UnityWebRequestWWW/Public/WWW.cs:113)
GlobalstatsIO.share (System.String id, System.String name, System.Collections.Generic.Dictionary2 values) (at Assets/Scripts/GlobalstatsIO.cs:151)`

I think it has to do with `Line 147: headers.Add ("Content-Length", json_payload.Length.ToString ());`

When I comment-out that line, I get a different error:
`WWW POST Content: {"code":400,"message":"bad_request","data":"No valid elements supplied"}
UnityEngine.Debug:Log(Object)
GlobalstatsIO:share(String, String, Dictionary2) (at Assets/Scripts/GlobalstatsIO.cs:162)`

**Comment by lobermann** [comment]
Hi @frankhan95 

Thanks for reporting this.
Is it possible for you to share the code sample that reproduces this? Or any other steps to make sure I can reproduce it?

Thanks,
Lukas

**Comment by SimanisMikoss** [comment]
Hi, @lobermann 

I've encountered the same error. Perhaps I'm doing something terribly wrong (very inexperienced programmer) :D 

Here's the script that calls a method from the library:
```c#
public class Leaderboard : MonoBehaviour
{
	GlobalstatsIO gs = new GlobalstatsIO();

	string user_name = "AlusTest1";
	Dictionary<string, string> playerStats = new Dictionary<string, string>();

	public void SumbmitStats()
	{
		playerStats.Add("expNorm", PlayerData.current.currentExp.ToString());

		if (gs.share("", user_name, playerStats))
		{
			// Success
			Debug.Log("success");
		}
		else
		{
			// An Error occured
			Debug.Log("fail");
		}
	}
}
```

Additional info
- ```SumbmitStats()``` is called when the player clicks on a UI button
- using Unity version 2018.2.14f1
- I've set ```api_id``` and ```api_secret``` in a script that runs on startup.

**Comment by lobermann** [comment]
@NeguliSimanis thanks! I will use that to reproduce, let's see.

**Comment by Rickmanx** [comment]
I too am getting the same error, and I've narrowed it down to this line in the share() method:

WWW www = new WWW (url, pData, headers);

It's using these parameters:
url = https://api.globalstats.io/v1/statistics
pData = {"name":"rick.testis","values":{"NormalHighestScores1":"1800"}}

headers = Dictionary of these values.
["Authorization"] = "Bearer [AUTH CODE]"
["Content-Type"] = "application/json"
["Content-Length"] = "54"

Raw View = Count=3

Can you tell me what I'm doing wrong?  Or can we get a fix on this?  I'd really to be able to use class if possible.

Thanks!

**Comment by swenmeeuwes** [comment]
I had the same problem.
After some puzzling I was able to fix it by:
1. Commenting the following line out: `headers.Add ("Content-Length", json_payload.Length.ToString ());` since this will be done automatically.
2. Correctly setting up the GTD's (under the 'My Games' tab), for @Rickmanx that would be setting up the `NormalHighestScores1` GTD. See image below for an example of a configured GTD, the key `time` is the key I put in the values dictionary.

![image](https://user-images.githubusercontent.com/11060870/63218009-19bf7400-c151-11e9-9723-4dbe6ab6b3dc.png)


After that it seems to work!

**Comment by lobermann** [comment]
I went ahead and removed that one line. So that should fix this issue.

**Comment by skoander** [comment]
@lobermann this issue still persists for the other API calls in the script. The `headers.Add("Content-Length", json_payload.Length.ToString());` line is also present in `linkStatistic` and `getLeaderboard`, causing the same error there.

**Comment by lobermann** [comment]
@notredamstra thank you very much for letting me know. Will fix it shortly in this repo.

**Comment by skoander** [comment]
@lobermann no problem. I recently forked this repo and was thinking about refactoring the deprecated WWW to UnityWebRequests, but I'll put that on hold if you're planning on doing some refactoring.

**Comment by lobermann** [comment]
@notredamstra nice, feel free to do so! Would appreciate it! It is just a small change and that can wait. I also think people will check in here if they encounter it.
